#!/bin/bash

echo "Running pre-commit hook... Current directory: $(pwd)"

if ! make pre-commit; then
    echo "`make pre-commit` failed. Commit aborted."
    exit 1
fi

echo "Pre-commit checks passed."
