package genx

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestFormatGo(t *testing.T) {
	{
		code := `package main
import (
"context"
"log"
	"os"
)

func main() {
log.Println("hello world")
}`
		want := `package main

import (
	"log"
)

func main() {
	log.Println("hello world")
}
`
		got, err := FormatGo(code)
		require.NoError(t, err)
		if !assert.Equal(t, want, got) {
			t.Log(got)
		}
	}

	{
		// with DO NOT EDIT comment
		code := `
// Code generated by github.com/molon/genx, DO NOT EDIT.
package main
import (
"context"
"log"
	"os"
)

func main() {
log.Println("hello world")
}`
		want := `// Code generated by github.com/molon/genx, DO NOT EDIT.
package main

import (
	"log"
)

func main() {
	log.Println("hello world")
}
`
		got, err := FormatGo(code)
		require.NoError(t, err)
		if !assert.Equal(t, want, got) {
			t.Log(got)
		}
	}
}
